const vesselTypes: Record<string, string> = {
	'0': 'Not available (default)',
	'20': 'Wing in ground (WIG)',
	'21': 'Wing in ground (WIG), Hazardous category A',
	'22': 'Wing in ground (WIG), Hazardous category B',
	'23': 'Wing in ground (WIG), Hazardous category C',
	'24': 'Wing in ground (WIG), Hazardous category D',
	'30': 'Fishing',
	'31': 'Towing',
	'32': 'Towing: length exceeds 200m or breadth exceeds 25m',
	'33': 'Dredging or underwater ops',
	'34': 'Diving ops',
	'35': 'Military ops',
	'36': 'Sailing',
	'37': 'Pleasure Craft',
	'40': 'High speed craft (HSC)',
	'50': 'Pilot Vessel',
	'51': 'Search and Rescue vessel',
	'52': 'Tug',
	'53': 'Port Tender',
	'54': 'Anti-pollution equipment',
	'55': 'Law Enforcement',
	'58': 'Medical Transport',
	'60': 'Passenger',
	'61': 'Passenger, Hazardous category A',
	'62': 'Passenger, Hazardous category B',
	'63': 'Passenger, Hazardous category C',
	'64': 'Passenger, Hazardous category D',
	'69': 'Passenger, No additional information',
	'70': 'Cargo',
	'71': 'Cargo, Hazardous category A',
	'72': 'Cargo, Hazardous category B',
	'73': 'Cargo, Hazardous category C',
	'74': 'Cargo, Hazardous category D',
	'79': 'Cargo, No additional information',
	'80': 'Tanker',
	'81': 'Tanker, Hazardous category A',
	'82': 'Tanker, Hazardous category B',
	'83': 'Tanker, Hazardous category C',
	'84': 'Tanker, Hazardous category D',
	'89': 'Tanker, No additional information',
};

export default function getShipType(number: number | string): string {
	return vesselTypes[number.toString()] ?? 'Unknown';
}
